# Generated by Django 5.2.5 on 2026-04-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_etudiantprofile_bulletin_notebulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('immatriculation', models.CharField(max_length=40, unique=True)),
                ('chauffeur', models.CharField(blank=True, max_length=120)),
                ('telephone_chauffeur', models.CharField(blank=True, max_length=30)),
                ('capacite', models.PositiveSmallIntegerField(default=20)),
                ('actif', models.BooleanField(default=True)),
                ('observations', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car de transport',
                'verbose_name_plural': 'Cars de transport',
                'ordering': ('nom', 'immatriculation'),
            },
        ),
    ]
