# Generated by Django 5.2.5 on 2026-04-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_cartransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartransport',
            name='axe_principal',
            field=models.CharField(choices=[('cocody', 'Cocody'), ('yopougon', 'Yopougon'), ('bingerville', 'Bingerville'), ('abobo', 'Abobo'), ('bassam', 'Bassam')], default='cocody', max_length=20),
        ),
        migrations.CreateModel(
            name='InscriptionTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axe', models.CharField(choices=[('cocody', 'Cocody'), ('yopougon', 'Yopougon'), ('bingerville', 'Bingerville'), ('abobo', 'Abobo'), ('bassam', 'Bassam')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('suspendue', 'Suspendue')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='administration.cartransport')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_transport', to='administration.etudiantprofile')),
            ],
            options={
                'verbose_name': 'Inscription transport',
                'verbose_name_plural': 'Inscriptions transport',
                'ordering': ('-created_at',),
                'unique_together': {('etudiant', 'axe')},
            },
        ),
    ]
