# Generated by Django 6.0.4 on 2026-05-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_cartransport_axe_principal_inscriptiontransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantprofile',
            name='annee_entree',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='etudiantprofile',
            name='matricule',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
