# Generated by Django 6.0.4 on 2026-05-03 19:06

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_etudiantprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantprofile',
            name='annee_entree',
            field=models.PositiveSmallIntegerField(default=administration.models.current_academic_entry_year),
        ),
        migrations.AlterField(
            model_name='etudiantprofile',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
