# Generated by Django 6.0.4 on 2026-05-03 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_etudiantprofile_annee_entree_and_more'),
        ('bibliotheque', '0002_filiere_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='administration.creneauabsence')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='administration.etudiantprofile')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='bibliotheque.matiere')),
            ],
            options={
                'ordering': ('-date', 'creneau__ordre', 'etudiant__matricule'),
                'unique_together': {('etudiant', 'matiere', 'date', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(max_length=1000)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='presences/justifications/%Y/%m/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee')], default='en_attente', max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='administration.presence')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
