# Generated by Codex on 2026-05-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0009_presence_justification"),
        ("bibliotheque", "0002_filiere_cycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seances",
                        to="bibliotheque.filiere",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seances",
                        to="bibliotheque.matiere",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seances",
                        to="administration.professeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seance",
                "verbose_name_plural": "Seances",
                "ordering": ("date", "heure_debut", "matiere__nom"),
                "unique_together": {("filiere", "matiere", "professeur", "date", "heure_debut", "heure_fin")},
            },
        ),
        migrations.AddField(
            model_name="presence",
            name="seance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presences",
                to="administration.seance",
            ),
        ),
    ]
