# Generated by Codex on 2026-05-03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0010_seance_presence_seance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=180)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("examen", "Examen"),
                            ("concours", "Concours"),
                            ("activite", "Activite"),
                            ("autre", "Autre"),
                        ],
                        default="conference",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                ("lieu", models.CharField(max_length=180)),
                ("public_cible", models.CharField(default="Tous", max_length=180)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("annule", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("date", "heure", "titre")},
        ),
        migrations.CreateModel(
            name="Scolarite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_du", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("date_echeance", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scolarite",
                        to="administration.etudiantprofile",
                    ),
                ),
            ],
            options={"ordering": ("etudiant__matricule",)},
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "moyen",
                    models.CharField(
                        choices=[
                            ("especes", "Especes"),
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("virement", "Virement"),
                            ("carte", "Carte bancaire"),
                        ],
                        default="especes",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("reference", models.CharField(max_length=80, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_attente", "En attente"), ("verifie", "Verifie"), ("rejete", "Rejete")],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scolarite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="administration.scolarite",
                    ),
                ),
            ],
            options={"ordering": ("-date", "-created_at")},
        ),
    ]
