from django.urls import path

from .views import (
    BibliothequeModerationView,
    BulletinPdfByMatriculeView,
    DashboardView,
    DossierDetailView,
    EmploisDuTempsExcelView,
    EmploisDuTempsPdfView,
    EmploisDuTempsView,
    EtudiantDetailView,
    EtudiantsListeView,
    EvenementsView,
    GlobalSearchView,
    InscriptionsView,
    NotesSaisieView,
    NotesView,
    PaiementsView,
    ParametresPaiementsView,
    ParametresTarifsView,
    ParametresView,
    PresencesView,
    ProfesseursView,
    AdminProfileView,
    TransportCarsView,
    UtilisateursView,
)

app_name = "administration"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("profil/", AdminProfileView.as_view(), name="profil_admin"),
    path("recherche/", GlobalSearchView.as_view(), name="global_search"),
    path("bulletins/pdf/", BulletinPdfByMatriculeView.as_view(), name="bulletin_pdf_matricule"),
    path("professeurs/", ProfesseursView.as_view(), name="professeurs"),
    path("etudiants/", EtudiantsListeView.as_view(), name="etudiants_liste"),
    path("etudiants/detail/", EtudiantDetailView.as_view(), name="etudiant_detail_legacy"),
    path("etudiants/<int:etudiant_id>/", EtudiantDetailView.as_view(), name="etudiant_detail"),
    path("notes/etudiant/<int:etudiant_id>/", EtudiantDetailView.as_view(), name="notes_etudiant"),
    path("inscriptions/", InscriptionsView.as_view(), name="inscriptions"),
    path("inscriptions/dossier/", DossierDetailView.as_view(), name="dossier_detail"),
    path("inscriptions/dossier/<int:dossier_id>/", DossierDetailView.as_view(), name="dossier_detail"),
    path("paiements/", PaiementsView.as_view(), name="paiements"),
    path("transport/cars/", TransportCarsView.as_view(), name="transport_cars"),
    path("notes/", NotesView.as_view(), name="notes"),
    path("notes/saisie/", NotesSaisieView.as_view(), name="notes_saisie"),
    path("presences/", PresencesView.as_view(), name="presences"),
    path("emplois-du-temps/", EmploisDuTempsView.as_view(), name="emplois_du_temps"),
    path("emplois-du-temps/export/excel/", EmploisDuTempsExcelView.as_view(), name="emplois_du_temps_export_excel"),
    path("emplois-du-temps/export/pdf/", EmploisDuTempsPdfView.as_view(), name="emplois_du_temps_export_pdf"),
    path("evenements/", EvenementsView.as_view(), name="evenements"),
    path("bibliotheque-moderation/", BibliothequeModerationView.as_view(), name="bibliotheque_moderation"),
    path("utilisateurs/", UtilisateursView.as_view(), name="utilisateurs"),
    path("parametres/", ParametresView.as_view(), name="parametres"),
    path("parametres/tarifs/", ParametresTarifsView.as_view(), name="parametres_tarifs"),
    path("parametres/paiements/", ParametresPaiementsView.as_view(), name="parametres_paiements"),
]
