# Generated by Django 6.0.4 on 2026-05-03 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0008_alter_etudiantprofile_annee_entree_and_more'),
        ('bibliotheque', '0002_filiere_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('validee', 'Validee'), ('refusee', 'Refusee'), ('incomplete', 'Incomplete')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscription_source', to='administration.etudiantprofile')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='bibliotheque.filiere')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='bibliotheque.licence')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_candidat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_soumission', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_requis', models.PositiveSmallIntegerField(default=6)),
                ('documents_fournis', models.PositiveSmallIntegerField(default=0)),
                ('commentaire_interne', models.TextField(blank=True)),
                ('motif_refus', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='inscription.inscription')),
            ],
            options={
                'ordering': ('-inscription__date_soumission',),
            },
        ),
    ]
