# Generated by Codex on 2026-05-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0002_filiere_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="matiere",
            name="semestre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matieres",
                to="bibliotheque.semestre",
            ),
        ),
    ]
